name: smart_farm
description: 'Precision Farming using on-device ML and AI'
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  cloud_firestore: ^5.1.0
  firebase_analytics: ^11.2.1
  firebase_app_check: ^0.3.0+4
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_performance: ^0.10.0+4
  firebase_vertexai: ^0.2.2+2
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.1.0
  flutter_gemma: ^0.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_image_labeling: ^0.12.0
  google_mlkit_object_detection: ^0.13.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  mockito: ^5.4.4
  path: any
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/launcher.png'
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
